import { LitElement,css,html,nothing } from 'lit';
import type { CreateRecipe,Ingredient,Instruction,Recipe } from '@foodz/contracts';
import phosphorRegular from '@phosphor-icons/web/regular?inline';
import phosphorBold from '@phosphor-icons/web/bold?inline';
import phosphorFill from '@phosphor-icons/web/fill?inline';
import { api } from '../services/api-client.js';

type View='list'|'detail'|'form'; type Draft={name:string;by:string;description:string;rating:number;tags:string;originUrl:string;ingredients:Ingredient[];instructions:Instruction[]};
const emptyDraft=():Draft=>({name:'',by:'',description:'',rating:0,tags:'',originUrl:'',ingredients:[{pos:1,group:'Ingredients',name:'',amount:'',unit:''}],instructions:[{pos:1,group:'Instructions',description:''}]});
export class FoodzApp extends LitElement{
  protected createRenderRoot(): HTMLElement | DocumentFragment {
    const root=super.createRenderRoot();
    const iconStyles=document.createElement('style');
    iconStyles.textContent=`${phosphorRegular}\n${phosphorBold}\n${phosphorFill}`;
    root.append(iconStyles);
    return root;
  }
  static properties={view:{state:true},recipes:{state:true},selected:{state:true},draft:{state:true},loading:{state:true},query:{state:true},message:{state:true}};
  declare view:View;declare recipes:Recipe[];declare selected:Recipe|null;declare draft:Draft;declare loading:boolean;declare query:string;declare message:string;
  constructor(){super();this.view='list';this.recipes=[];this.selected=null;this.draft=emptyDraft();this.loading=false;this.query='';this.message='';}
  connectedCallback(){super.connectedCallback();void this.load();}
  async load(){this.loading=true;try{this.recipes=await api.list(this.query);}catch(e){this.notify(e);}finally{this.loading=false;}}
  notify(value:unknown){this.message=value instanceof Error?value.message:String(value);window.setTimeout(()=>this.message='',3500);}
  edit(recipe?:Recipe){this.selected=recipe??null;this.draft=recipe?{...recipe,tags:recipe.tags.join(', '),ingredients:recipe.ingredients.map(x=>({...x})),instructions:recipe.instructions.map(x=>({...x}))}:emptyDraft();this.view='form';}
  field<K extends keyof Draft>(key:K,value:Draft[K]){this.draft={...this.draft,[key]:value};}
  ingredient(index:number,key:keyof Ingredient,value:string){const ingredients=this.draft.ingredients.map((item,i)=>i===index?{...item,[key]:value}:item);this.field('ingredients',ingredients);}
  instruction(index:number,value:string){const instructions=this.draft.instructions.map((item,i)=>i===index?{...item,description:value}:item);this.field('instructions',instructions);}
  async save(event:SubmitEvent){event.preventDefault();const payload:CreateRecipe={userID:this.selected?.userID??'665544332211009988776655',name:this.draft.name.trim(),by:this.draft.by.trim(),description:this.draft.description.trim(),rating:Number(this.draft.rating),originUrl:this.draft.originUrl.trim(),tags:this.draft.tags.split(',').map(x=>x.trim()).filter(Boolean),isPublic:true,ingredients:this.draft.ingredients.filter(x=>x.name.trim()).map((x,i)=>({...x,pos:i+1,name:x.name.trim()})),instructions:this.draft.instructions.filter(x=>x.description.trim()).map((x,i)=>({...x,pos:i+1,description:x.description.trim()}))};try{this.selected?await api.update(this.selected._id,payload):await api.create(payload);this.view='list';await this.load();}catch(e){this.notify(e);}}
  remove(recipe?:Recipe):void { if(!recipe){super.remove();return;} void this.deleteRecipe(recipe); }
  private async deleteRecipe(recipe:Recipe){if(!confirm(`Delete “${recipe.name}”?`))return;try{await api.delete(recipe._id);if(this.selected?._id===recipe._id)this.view='list';await this.load();}catch(e){this.notify(e);}}
  render(){return html`<header><button class="brand" @click=${()=>{this.view='list';void this.load();}}><i class="ph-bold ph-cooking-pot"></i><span>Foodz</span></button><span class="badge">Lit + Hono</span></header>${this.message?html`<aside role="alert">${this.message}</aside>`:nothing}<main>${this.view==='list'?this.list():this.view==='detail'?this.detail():this.form()}</main>`;}
  list(){return html`<section class="toolbar"><label class="search"><i class="ph ph-magnifying-glass"></i><input aria-label="Search recipes" placeholder="Search recipes…" .value=${this.query} @change=${(e:Event)=>{this.query=(e.target as HTMLInputElement).value;void this.load();}}></label><button class="primary" @click=${()=>this.edit()}><i class="ph-bold ph-plus"></i>New recipe</button></section>${this.loading?html`<p class="empty">Loading…</p>`:this.recipes.length?html`<section class="grid">${this.recipes.map(recipe=>html`<article><div class="card-top"><i class="ph ph-bowl-food"></i><span>${recipe.rating.toFixed(1)} <i class="ph-fill ph-star"></i></span></div><h2>${recipe.name}</h2><p>${recipe.description||'No description yet.'}</p><div class="tags">${recipe.tags.map(tag=>html`<span>#${tag}</span>`)}</div><footer><button @click=${()=>{this.selected=recipe;this.view='detail';}}>View</button><button title="Edit" @click=${()=>this.edit(recipe)}><i class="ph ph-pencil-simple"></i></button><button title="Delete" @click=${()=>void this.remove(recipe)}><i class="ph ph-trash"></i></button></footer></article>`)}</section>`:html`<p class="empty">No recipes found. Add the first one!</p>`}`;}
  detail(){const r=this.selected;if(!r)return nothing;return html`<section class="panel"><nav><button @click=${()=>this.view='list'}><i class="ph ph-arrow-left"></i>Back</button><button class="primary" @click=${()=>this.edit(r)}><i class="ph ph-pencil-simple"></i>Edit</button></nav><h1>${r.name}</h1><p>${r.by?`By ${r.by} · `:''}${r.rating.toFixed(1)} stars</p><p>${r.description}</p><div class="columns"><div><h2>Ingredients</h2><ul>${r.ingredients.map(x=>html`<li><span>${x.name}</span><strong>${x.amount} ${x.unit}</strong></li>`)}</ul></div><div><h2>Instructions</h2><ol>${r.instructions.map(x=>html`<li>${x.description}</li>`)}</ol></div></div>${r.originUrl?html`<a href=${r.originUrl} target="_blank" rel="noopener">Original recipe <i class="ph ph-arrow-square-out"></i></a>`:nothing}</section>`;}
  form(){return html`<form class="panel" @submit=${this.save}><nav><h1>${this.selected?'Edit recipe':'New recipe'}</h1><button type="button" @click=${()=>this.view=this.selected?'detail':'list'}>Cancel</button></nav><label>Name<input required .value=${this.draft.name} @input=${(e:Event)=>this.field('name',(e.target as HTMLInputElement).value)}></label><div class="columns"><label>Author<input .value=${this.draft.by} @input=${(e:Event)=>this.field('by',(e.target as HTMLInputElement).value)}></label><label>Rating<input type="number" min="0" max="5" step=".5" .value=${String(this.draft.rating)} @input=${(e:Event)=>this.field('rating',Number((e.target as HTMLInputElement).value))}></label></div><label>Description<textarea .value=${this.draft.description} @input=${(e:Event)=>this.field('description',(e.target as HTMLTextAreaElement).value)}></textarea></label><div class="columns"><label>Tags<input placeholder="quick, dinner" .value=${this.draft.tags} @input=${(e:Event)=>this.field('tags',(e.target as HTMLInputElement).value)}></label><label>Origin URL<input type="url" .value=${this.draft.originUrl} @input=${(e:Event)=>this.field('originUrl',(e.target as HTMLInputElement).value)}></label></div><h2>Ingredients</h2>${this.draft.ingredients.map((x,i)=>html`<div class="row"><input aria-label="Ingredient" placeholder="Ingredient" .value=${x.name} @input=${(e:Event)=>this.ingredient(i,'name',(e.target as HTMLInputElement).value)}><input aria-label="Amount" placeholder="Amount" .value=${String(x.amount)} @input=${(e:Event)=>this.ingredient(i,'amount',(e.target as HTMLInputElement).value)}><input aria-label="Unit" placeholder="Unit" .value=${x.unit} @input=${(e:Event)=>this.ingredient(i,'unit',(e.target as HTMLInputElement).value)}></div>`)}<button type="button" @click=${()=>this.field('ingredients',[...this.draft.ingredients,{pos:this.draft.ingredients.length+1,group:'Ingredients',name:'',amount:'',unit:''}])}>+ Ingredient</button><h2>Instructions</h2>${this.draft.instructions.map((x,i)=>html`<input aria-label="Instruction ${i+1}" placeholder="Step ${i+1}" .value=${x.description} @input=${(e:Event)=>this.instruction(i,(e.target as HTMLInputElement).value)}>`)}<button type="button" @click=${()=>this.field('instructions',[...this.draft.instructions,{pos:this.draft.instructions.length+1,group:'Instructions',description:''}])}>+ Step</button><footer><button class="primary" type="submit"><i class="ph ph-floppy-disk"></i>Save recipe</button></footer></form>`;}
  static styles=css`:host{display:block;max-width:1080px;margin:auto;padding:2rem 1.25rem}header{display:flex;align-items:center;gap:.7rem;border-bottom:1px solid #334155;padding-bottom:1.5rem;margin-bottom:2rem}.brand{border:0;background:none;color:#f8fafc;font:700 1.8rem Outfit;display:flex;gap:.6rem;align-items:center}.brand i,h2,.panel>a{color:#fb923c}.badge,.tags span{font-size:.78rem;color:#fb923c;background:#f9731622;border:1px solid #f9731644;border-radius:20px;padding:.25rem .6rem}aside{position:fixed;right:1rem;top:1rem;background:#ef4444;color:white;padding:1rem;border-radius:.6rem;z-index:2}.toolbar,nav,footer,.row{display:flex;gap:.7rem;align-items:center}.toolbar{justify-content:space-between;margin-bottom:1.5rem}.search{display:flex;align-items:center;background:#1e293b;border:1px solid #334155;border-radius:.6rem;padding:0 .8rem;flex:1;max-width:32rem}.search input{border:0}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:1rem}article,.panel{background:#1e293b;border:1px solid #334155;border-radius:1rem;padding:1.4rem;box-shadow:0 10px 25px #0003}article p{color:#94a3b8;min-height:3em}.card-top,article footer{display:flex;justify-content:space-between}.card-top>i{font-size:2rem;color:#fb923c}.ph-star{color:#f59e0b}.tags{display:flex;gap:.35rem;flex-wrap:wrap;min-height:2rem}article footer{border-top:1px solid #334155;margin-top:1rem;padding-top:1rem}button{border:1px solid #475569;background:#334155;color:#f8fafc;border-radius:.5rem;padding:.58rem .85rem}.primary{background:#ea580c;border-color:#f97316;font-weight:600}button i{margin-right:.35rem}.panel{max-width:850px;margin:auto}.panel nav{justify-content:space-between}.panel h1{font:700 2rem Outfit}.columns{display:grid;grid-template-columns:1fr 1fr;gap:1.5rem}.panel li{padding:.45rem}.panel ul li{display:flex;justify-content:space-between;border-bottom:1px dashed #475569}label{display:grid;gap:.4rem;color:#cbd5e1;font-weight:600;margin:1rem 0}input,textarea{width:100%;background:#0f172a;border:1px solid #475569;border-radius:.5rem;color:#f8fafc;padding:.75rem}textarea{min-height:6rem}.row input:first-child{flex:2}.panel footer{justify-content:flex-end;margin-top:1.5rem}.empty{text-align:center;color:#94a3b8;padding:4rem}@media(max-width:650px){.columns{grid-template-columns:1fr}.toolbar{align-items:stretch;flex-direction:column}.row{display:grid;grid-template-columns:2fr 1fr 1fr}}`;
}
customElements.define('foodz-app',FoodzApp);
